import Header from './components/Header';
import './globals.css'
import { League_Spartan } from 'next/font/google'

const spartan = League_Spartan({ subsets: ["latin"] });


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${spartan.className} bg-background text-white`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
