import './globals.css'
import { Antonio, League_Spartan } from 'next/font/google'

const antonio = Antonio({ subsets: ["latin"] });
const spartan = League_Spartan({ subsets: ["latin"] });


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={spartan.className}>{children}</body>
    </html>
  )
}
